"""Build static GitHub Pages files for Store privacy/support URLs."""

from __future__ import annotations

import argparse
import html
import re
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_BLOB_URL = "https://github.com/dev-bricks/CareCenter-for-Codex/blob/main"
OUTPUT_MARKER = ".carecenter-pages-build"
LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD_PATTERN = re.compile(r"\*\*([^*]+)\*\*")
PAGES = {
    "privacy": {
        "source": "docs/privacy.md",
        "title": "Privacy - CareCenter for Codex",
    },
    "support": {
        "source": "docs/support.md",
        "title": "Support - CareCenter for Codex",
    },
}


def _rewrite_href(href: str) -> str:
    normalized = href.strip()
    local_routes = {
        "./privacy.md": "../privacy/",
        "privacy.md": "../privacy/",
        "./support.md": "../support/",
        "support.md": "../support/",
        "../PRIVACY_POLICY.md": f"{REPOSITORY_BLOB_URL}/PRIVACY_POLICY.md",
        "../SUPPORT.md": f"{REPOSITORY_BLOB_URL}/SUPPORT.md",
    }
    return local_routes.get(normalized, normalized)


def _render_plain(text: str) -> str:
    escaped = html.escape(text, quote=False)
    return BOLD_PATTERN.sub(r"<strong>\1</strong>", escaped)


def _render_inline(text: str) -> str:
    parts: list[str] = []
    cursor = 0
    for match in LINK_PATTERN.finditer(text):
        parts.append(_render_plain(text[cursor : match.start()]))
        label = _render_plain(match.group(1))
        href = html.escape(_rewrite_href(match.group(2)), quote=True)
        parts.append(f'<a href="{href}">{label}</a>')
        cursor = match.end()
    parts.append(_render_plain(text[cursor:]))
    return "".join(parts)


def _close_list(lines: list[str], list_open: bool) -> bool:
    if list_open:
        lines.append("</ul>")
    return False


def render_markdown(markdown: str) -> str:
    lines: list[str] = []
    list_open = False
    paragraph: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph
        if not paragraph:
            return
        lines.append(f"<p>{_render_inline(' '.join(paragraph))}</p>")
        paragraph = []

    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            list_open = _close_list(lines, list_open)
            continue
        if stripped == "---":
            flush_paragraph()
            list_open = _close_list(lines, list_open)
            lines.append("<hr>")
            continue
        if stripped.startswith("### "):
            flush_paragraph()
            list_open = _close_list(lines, list_open)
            lines.append(f"<h3>{_render_inline(stripped[4:])}</h3>")
            continue
        if stripped.startswith("## "):
            flush_paragraph()
            list_open = _close_list(lines, list_open)
            lines.append(f"<h2>{_render_inline(stripped[3:])}</h2>")
            continue
        if stripped.startswith("# "):
            flush_paragraph()
            list_open = _close_list(lines, list_open)
            lines.append(f"<h1>{_render_inline(stripped[2:])}</h1>")
            continue
        if stripped.startswith("- "):
            flush_paragraph()
            if not list_open:
                lines.append("<ul>")
                list_open = True
            lines.append(f"<li>{_render_inline(stripped[2:])}</li>")
            continue
        paragraph.append(stripped)

    flush_paragraph()
    _close_list(lines, list_open)
    return "\n".join(lines)


def _page_html(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
    :root {{ color-scheme: light dark; }}
    body {{
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
      max-width: 860px;
      margin: 0 auto;
      padding: 40px 20px;
    }}
    a {{ color: #2563eb; }}
    h1, h2, h3 {{ line-height: 1.25; }}
    hr {{ border: 0; border-top: 1px solid #d4d4d8; margin: 28px 0; }}
    li {{ margin: 6px 0; }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""


def _reset_output_dir(output_dir: Path) -> None:
    if output_dir.exists():
        marker = output_dir / OUTPUT_MARKER
        if not marker.exists():
            raise RuntimeError(f"Refusing to replace unmarked output directory: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    (output_dir / OUTPUT_MARKER).write_text("generated by scripts/build_store_pages.py\n", encoding="utf-8")


def build_pages(project_root: Path = PROJECT_ROOT, output_dir: Path | None = None) -> list[Path]:
    target = output_dir or project_root / "_site"
    _reset_output_dir(target)
    written: list[Path] = []

    for slug, spec in PAGES.items():
        source = project_root / spec["source"]
        markdown = source.read_text(encoding="utf-8")
        destination = target / slug / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            _page_html(spec["title"], render_markdown(markdown)),
            encoding="utf-8",
        )
        written.append(destination)

    index = target / "index.html"
    index.write_text(
        _page_html(
            "CareCenter for Codex Store pages",
            '<h1>CareCenter for Codex Store pages</h1>\n'
            '<ul>\n<li><a href="privacy/">Privacy</a></li>\n'
            '<li><a href="support/">Support</a></li>\n</ul>',
        ),
        encoding="utf-8",
    )
    written.append(index)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    written = build_pages(args.project_root.resolve(), args.output.resolve() if args.output else None)
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
